import { Attack } from "./types"

export const attacks: { [key: string]: Attack } = {
  slash: {
    template: "slash",
    name: "Slash",
    attackType: "Physical",
    effects: ["BUFF"],
    chanceToLand: 0.95,
    damage: 10,
    trueDamage: 0,
    icon: "sword_icon",
    notes: "Basic physical attack with a chance for a critical hit.",
    cooldown: 1,
  },
  pierce: {
    template: "pierce",
    name: "Pierce",
    attackType: "Physical",
    effects: [],
    chanceToLand: 0.9,
    damage: 12,
    trueDamage: 0,
    icon: "spear_icon",
    notes: "Attack that penetrates enemy armor.",
    cooldown: 2,
  },
  rend: {
    template: "rend",
    name: "Rend",
    attackType: "Physical",
    effects: ["POISON"],
    chanceToLand: 0.85,
    damage: 8,
    trueDamage: 2,
    icon: "axe_icon",
    notes: "Attack that causes bleeding over time.",
    cooldown: 3,
  },
  bash: {
    template: "bash",
    name: "Bash",
    attackType: "Physical",
    effects: ["STUN"],
    chanceToLand: 0.9,
    damage: 15,
    trueDamage: 0,
    icon: "hammer_icon",
    notes: "A strong attack that may stun the enemy.",
    cooldown: 2,
  },
  fireball: {
    template: "fireball",
    name: "Fireball",
    attackType: "Elemental",
    effects: ["BURN"],
    chanceToLand: 0.9,
    damage: 20,
    trueDamage: 5,
    icon: "fireball_icon",
    notes: "Deals fire damage with a chance to burn the target.",
    cooldown: 3,
  },
  thunderbolt: {
    template: "thunderbolt",
    name: "Thunderbolt",
    attackType: "Elemental",
    effects: ["STUN"],
    chanceToLand: 0.85,
    damage: 18,
    trueDamage: 4,
    icon: "lightning_icon",
    notes: "Deals electric damage with a chance to paralyze.",
    cooldown: 3,
  },
  ice_shard: {
    template: "ice_shard",
    name: "Ice Shard",
    attackType: "Elemental",
    effects: [],
    chanceToLand: 0.95,
    damage: 10,
    trueDamage: 0,
    icon: "ice_icon",
    notes: "Basic ice attack with high accuracy.",
    cooldown: 1,
  },
  shockwave: {
    template: "shockwave",
    name: "Shockwave",
    attackType: "Elemental",
    effects: [],
    chanceToLand: 0.8,
    damage: 14,
    trueDamage: 2,
    icon: "shockwave_icon",
    notes: "Earth attack that may shock the enemy.",
    cooldown: 2,
  },
  venom_strike: {
    template: "venom_strike",
    name: "Venom Strike",
    attackType: "Status",
    effects: ["POISON"],
    chanceToLand: 0.8,
    damage: 6,
    trueDamage: 3,
    icon: "poison_icon",
    notes: "Inflicts poison on the enemy.",
    cooldown: 3,
  },
  lullaby: {
    template: "lullaby",
    name: "Lullaby",
    attackType: "Status",
    effects: [],
    chanceToLand: 0.6,
    damage: 0,
    trueDamage: 0,
    icon: "sleep_icon",
    notes: "Puts the enemy to sleep.",
    cooldown: 4,
  },
  dizzying_blow: {
    template: "dizzying_blow",
    name: "Dizzying Blow",
    attackType: "Status",
    effects: ["STUN"],
    chanceToLand: 0.75,
    damage: 12,
    trueDamage: 1,
    icon: "confusion_icon",
    notes: "May confuse the enemy.",
    cooldown: 2,
  },
  weakening_touch: {
    template: "weakening_touch",
    name: "Weakening Touch",
    attackType: "Status",
    effects: [],
    chanceToLand: 0.85,
    damage: 5,
    trueDamage: 0,
    icon: "weakness_icon",
    notes: "Reduces enemy's attack power.",
    cooldown: 3,
  },
  heal: {
    template: "heal",
    name: "Heal",
    attackType: "SupportHealing",
    effects: ["REGENERATION"],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "heal_icon",
    notes: "Restores health to an ally over time.",
    cooldown: 2,
  },
  protect: {
    template: "protect",
    name: "Protect",
    attackType: "SupportHealing",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "shield_icon",
    notes: "Shields an ally, reducing incoming damage.",
    cooldown: 3,
  },
  purify: {
    template: "purify",
    name: "Purify",
    attackType: "SupportHealing",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "cure_icon",
    notes: "Removes negative status effects from an ally.",
    cooldown: 2,
  },
  revitalize: {
    template: "revitalize",
    name: "Revitalize",
    attackType: "SupportHealing",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "revitalize_icon",
    notes: "Restores a moderate amount of health instantly.",
    cooldown: 3,
  },
  arcane_blast: {
    template: "arcane_blast",
    name: "Arcane Blast",
    attackType: "Magical",
    effects: [],
    chanceToLand: 0.9,
    damage: 20,
    trueDamage: 0,
    icon: "arcane_icon",
    notes: "Deals magical damage to an enemy.",
    cooldown: 2,
  },
  mana_leech: {
    template: "mana_leech",
    name: "Mana Leech",
    attackType: "Magical",
    effects: [],
    chanceToLand: 0.85,
    damage: 10,
    trueDamage: 2,
    icon: "mana_icon",
    notes: "Drains mana from the enemy.",
    cooldown: 3,
  },
  spell_boost: {
    template: "spell_boost",
    name: "Spell Boost",
    attackType: "Magical",
    effects: ["BUFF"],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "magic_boost_icon",
    notes: "Increases caster's magic power.",
    cooldown: 4,
  },
  reflective_shield: {
    template: "reflective_shield",
    name: "Reflective Shield",
    attackType: "Magical",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "reflect_icon",
    notes: "Reflects enemy spells back at them.",
    cooldown: 5,
  },
  arrow_shot: {
    template: "arrow_shot",
    name: "Arrow Shot",
    attackType: "Ranged",
    effects: [],
    chanceToLand: 0.95,
    damage: 10,
    trueDamage: 0,
    icon: "arrow_icon",
    notes: "Basic ranged attack.",
    cooldown: 1,
  },
  snipe: {
    template: "snipe",
    name: "Snipe",
    attackType: "Ranged",
    effects: [],
    chanceToLand: 0.8,
    damage: 25,
    trueDamage: 5,
    icon: "long_arrow_icon",
    notes: "High damage at a distance.",
    cooldown: 3,
  },
  volley: {
    template: "volley",
    name: "Volley",
    attackType: "Ranged",
    effects: [],
    chanceToLand: 0.85,
    damage: 15,
    trueDamage: 0,
    icon: "multiple_arrows_icon",
    notes: "Attacks multiple enemies.",
    cooldown: 2,
  },
  penetrating_shot: {
    template: "penetrating_shot",
    name: "Penetrating Shot",
    attackType: "Ranged",
    effects: [],
    chanceToLand: 0.75,
    damage: 18,
    trueDamage: 0,
    icon: "piercing_arrow_icon",
    notes: "Ignores enemy defenses.",
    cooldown: 3,
  },
  battle_cry: {
    template: "battle_cry",
    name: "Battle Cry",
    attackType: "Support",
    effects: ["BUFF"],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "strength_icon",
    notes: "Boosts allies' attack power.",
    cooldown: 4,
  },
  fortify: {
    template: "fortify",
    name: "Fortify",
    attackType: "Support",
    effects: ["BUFF"],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "defense_icon",
    notes: "Boosts allies' defense.",
    cooldown: 4,
  },
  haste: {
    template: "haste",
    name: "Haste",
    attackType: "Support",
    effects: ["BUFF"],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "speed_icon",
    notes: "Boosts allies' speed.",
    cooldown: 3,
  },
  inspire: {
    template: "inspire",
    name: "Inspire",
    attackType: "Auras",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "inspire_icon",
    notes: "Boosts allies' morale.",
    cooldown: 5,
  },
  quicksand: {
    template: "quicksand",
    name: "Quicksand",
    attackType: "Trap",
    effects: ["STUN"],
    chanceToLand: 0.9,
    damage: 5,
    trueDamage: 0,
    icon: "quicksand_icon",
    notes: "Sets a trap that slows enemies.",
    cooldown: 3,
  },
  rain_dance: {
    template: "rain_dance",
    name: "Rain Dance",
    attackType: "Environmental",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "rain_icon",
    notes: "Changes weather to rain.",
    cooldown: 4,
  },
  rock_slide: {
    template: "rock_slide",
    name: "Rock Slide",
    attackType: "Environmental",
    effects: [],
    chanceToLand: 0.85,
    damage: 20,
    trueDamage: 0,
    icon: "rock_icon",
    notes: "Deals damage using the environment.",
    cooldown: 3,
  },
  camouflage: {
    template: "camouflage",
    name: "Camouflage",
    attackType: "Environmental",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "camouflage_icon",
    notes: "Uses terrain to hide and gain advantage.",
    cooldown: 5,
  },
  chrono_break: {
    template: "chrono_break",
    name: "Chrono Break",
    attackType: "Special",
    effects: ["STUN"],
    chanceToLand: 0.15,
    damage: 10,
    trueDamage: 0,
    icon: "time_icon",
    notes: "Attempts to stop time for enemies.",
    cooldown: 6,
  },
  phase_shift: {
    template: "phase_shift",
    name: "Phase Shift",
    attackType: "Special",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "teleport_icon",
    notes: "Evades attacks by teleporting.",
    cooldown: 4,
  },
  mirror_image: {
    template: "mirror_image",
    name: "Mirror Image",
    attackType: "Special",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "clone_icon",
    notes: "Creates clones to confuse enemies.",
    cooldown: 5,
  },
  ultimate_blast: {
    template: "ultimate_blast",
    name: "Ultimate Blast",
    attackType: "Special",
    effects: [],
    chanceToLand: 0.7,
    damage: 40,
    trueDamage: 5,
    icon: "blast_icon",
    notes: "A powerful attack with high damage.",
    cooldown: 6,
  },
  twin_slash: {
    template: "twin_slash",
    name: "Twin Slash",
    attackType: "Combo",
    effects: [],
    chanceToLand: 0.9,
    damage: 15,
    trueDamage: 0,
    icon: "double_sword_icon",
    notes: "Attacks twice in quick succession.",
    cooldown: 2,
  },
  whirlwind: {
    template: "whirlwind",
    name: "Whirlwind",
    attackType: "Combo",
    effects: [],
    chanceToLand: 0.85,
    damage: 18,
    trueDamage: 2,
    icon: "whirlwind_icon",
    notes: "Attacks multiple enemies in succession.",
    cooldown: 3,
  },
  elemental_burst: {
    template: "elemental_burst",
    name: "Elemental Burst",
    attackType: "Combo",
    effects: [],
    chanceToLand: 0.8,
    damage: 30,
    trueDamage: 5,
    icon: "fusion_icon",
    notes: "Combines elements for massive damage.",
    cooldown: 4,
  },
  flurry: {
    template: "flurry",
    name: "Flurry",
    attackType: "Combo",
    effects: [],
    chanceToLand: 0.95,
    damage: 12,
    trueDamage: 0,
    icon: "flurry_icon",
    notes: "Rapidly attacks the enemy multiple times.",
    cooldown: 2,
  },
  sneak_attack: {
    template: "sneak_attack",
    name: "Sneak Attack",
    attackType: "Stealth",
    effects: [],
    chanceToLand: 1.0,
    damage: 20,
    trueDamage: 5,
    icon: "dagger_icon",
    notes: "Deals high damage when undetected.",
    cooldown: 3,
  },
  vanish: {
    template: "vanish",
    name: "Vanish",
    attackType: "Stealth",
    effects: [],
    chanceToLand: 1.0,
    damage: 0,
    trueDamage: 0,
    icon: "invisibility_icon",
    notes: "Becomes invisible to enemies.",
    cooldown: 5,
  },
  silent_strike: {
    template: "silent_strike",
    name: "Silent Strike",
    attackType: "Stealth",
    effects: [],
    chanceToLand: 0.5,
    damage: 25,
    trueDamage: 10,
    icon: "silent_kill_icon",
    notes: "Chance to instantly defeat an enemy.",
    cooldown: 6,
  },
  shadow_step: {
    template: "shadow_step",
    name: "Shadow Step",
    attackType: "Stealth",
    effects: [],
    chanceToLand: 1.0,
    damage: 5,
    trueDamage: 0,
    icon: "shadow_icon",
    notes: "Moves swiftly, increasing evasion.",
    cooldown: 4,
  },
}

export const attackTypes = {
  Physical: [attacks.slash, attacks.pierce, attacks.rend, attacks.bash],
  Elemental: [
    attacks.fireball,
    attacks.thunderbolt,
    attacks.ice_shard,
    attacks.shockwave,
  ],
  Status: [
    attacks.venom_strike,
    attacks.lullaby,
    attacks.dizzying_blow,
    attacks.weakening_touch,
  ],
  SupportHealing: [
    attacks.heal,
    attacks.protect,
    attacks.purify,
    attacks.revitalize,
  ],
  Magical: [
    attacks.arcane_blast,
    attacks.mana_leech,
    attacks.spell_boost,
    attacks.reflective_shield,
  ],
  Ranged: [
    attacks.arrow_shot,
    attacks.snipe,
    attacks.volley,
    attacks.penetrating_shot,
  ],
  Special: [
    attacks.chrono_break,
    attacks.phase_shift,
    attacks.mirror_image,
    attacks.ultimate_blast,
  ],
  Combo: [
    attacks.twin_slash,
    attacks.whirlwind,
    attacks.elemental_burst,
    attacks.flurry,
  ],
  Stealth: [
    attacks.sneak_attack,
    attacks.vanish,
    attacks.silent_strike,
    attacks.shadow_step,
  ],
}

// // Example of how you might use these in a component
// import { attacks } from './attacks';

// function AttackButton({ attackId }) {
//   const attack = attacks[attackId];

//   return (
//     <div>
//       <button>
//         <img src={`/icons/${attack.icon}.png`} alt={attack.name} />
//         {attack.name}
//       </button>
//     </div>
//   );
// }

// export default AttackButton;
