export const MAX_HP = 100
const BASE_HEALTH = 100
const BASE_ATTACK = 20
const BASE_DEFENCE = 10
const BASE_TRUE_DAMAGE = 15
// Base stats for all creatures
const baseStats = {
  health: 100,
  attack: 20,
  defence: 10,
  trueDamage: 15,
}
// dragon: {
//   id: 1,
//   name: "Dragon",
//   icon: "🐉",
//   template: "dragon",
//   multipliers: {
//     health: 1.5, // Dragon has 150% base health
//     attack: 1.2, // Dragon has 120% base attack
//     defence: 1.0, // Dragon has 100% base defence
//     trueDamage: 1.3, // Dragon has 130% base true damage
//   },
//   mods: [],
// },
export const CREATURES = {
  dragon: {
    name: "Draco",
    icon: "🐉",
    template: "dragon",
    health: 250,
    maxHealth: 250,
    attack: 20,
    trueDamage: 90,
    defence: 5,
    mods: [],
  },
  unicorn: {
    name: "Sparkle",
    icon: "🦄",
    template: "unicorn",
    health: 200,
    maxHealth: 200,
    attack: 15,
    trueDamage: 10,
    defence: 5,
    mods: [],
  },
  alien: {
    name: "Zorg",
    icon: "👾",
    template: "alien",
    health: 180,
    maxHealth: 180,
    attack: 20,
    trueDamage: 15,
    defence: 8,
    mods: [],
  },
  fish: {
    name: "Octavia",
    icon: "🐙",
    template: "fish",
    health: 150,
    maxHealth: 150,
    attack: 10,
    trueDamage: 5,
    defence: 5,
    mods: [],
  },
  phoenix: {
    name: "Ash",
    icon: "🦅",
    template: "phoenix",
    health: 300,
    maxHealth: 300,
    attack: 30,
    trueDamage: 20,
    defence: 8,
    mods: [],
  },
  minotaur: {
    name: "Asterion",
    icon: "🐂",
    template: "minotaur",
    health: 400,
    maxHealth: 400,
    attack: 50,
    trueDamage: 25,
    defence: 15,
    mods: [],
  },
  werewolf: {
    name: "Fang",
    icon: "🐺",
    template: "werewolf",
    health: 350,
    maxHealth: 350,
    attack: 45,
    trueDamage: 20,
    defence: 10,
    mods: [],
  },
  giant: {
    name: "Goliath",
    icon: "👹",
    template: "giant",
    health: 500,
    maxHealth: 500,
    attack: 60,
    trueDamage: 40,
    defence: 20,
    mods: [],
  },
  golem: {
    name: "Rocky",
    icon: "🟠",
    template: "golem",
    health: 550,
    maxHealth: 550,
    attack: 30,
    trueDamage: 10,
    defence: 50,
    mods: [],
  },
  vampire: {
    name: "Vlad",
    icon: "🦛",
    template: "vampire",
    health: 300,
    maxHealth: 300,
    attack: 40,
    trueDamage: 15,
    defence: 10,
    mods: [],
  },
  cyclops: {
    name: "Argus",
    icon: "👁",
    template: "cyclops",
    health: 450,
    maxHealth: 450,
    attack: 55,
    trueDamage: 35,
    defence: 25,
    mods: [],
  },
  gryphon: {
    name: "Griff",
    icon: "🦅",
    template: "gryphon",
    health: 350,
    maxHealth: 350,
    attack: 35,
    trueDamage: 20,
    defence: 15,
    mods: [],
  },
  kraken: {
    name: "Kraken",
    icon: "🦑",
    template: "kraken",
    health: 600,
    maxHealth: 600,
    attack: 70,
    trueDamage: 50,
    defence: 20,
    mods: [],
  },
  pegasus: {
    name: "Wings",
    icon: "🦄",
    template: "pegasus",
    health: 300,
    maxHealth: 300,
    attack: 30,
    trueDamage: 10,
    defence: 20,
    mods: [],
  },
  banshee: {
    name: "Wail",
    icon: "👻",
    template: "banshee",
    health: 250,
    maxHealth: 250,
    attack: 20,
    trueDamage: 15,
    defence: 10,
    mods: [],
  },
  chimera: {
    name: "Chimmy",
    icon: "🐉",
    template: "chimera",
    health: 400,
    maxHealth: 400,
    attack: 50,
    trueDamage: 30,
    defence: 25,
    mods: [],
  },
  basilisk: {
    name: "Slither",
    icon: "🐍",
    template: "basilisk",
    health: 350,
    maxHealth: 350,
    attack: 40,
    trueDamage: 20,
    defence: 15,
    mods: [],
  },
  centaur: {
    name: "Cento",
    icon: "🐎",
    template: "centaur",
    health: 300,
    maxHealth: 300,
    attack: 35,
    trueDamage: 15,
    defence: 20,
    mods: [],
  },
  cerberus: {
    name: "Hades",
    icon: "🐶",
    template: "cerberus",
    health: 550,
    maxHealth: 550,
    attack: 60,
    trueDamage: 40,
    defence: 25,
    mods: [],
  },
  hydra: {
    name: "Hydro",
    icon: "🐍",
    template: "hydra",
    health: 500,
    maxHealth: 500,
    attack: 55,
    trueDamage: 35,
    defence: 20,
    mods: [],
  },
  sphinx: {
    name: "Riddle",
    icon: "🐯",
    template: "sphinx",
    health: 400,
    maxHealth: 400,
    attack: 45,
    trueDamage: 25,
    defence: 15,
    mods: [],
  },
  harpy: {
    name: "Harper",
    icon: "🦅",
    template: "harpy",
    health: 200,
    maxHealth: 200,
    attack: 15,
    trueDamage: 10,
    defence: 10,
    mods: [],
  },
  leviathan: {
    name: "Levi",
    icon: "🐋",
    template: "leviathan",
    health: 700,
    maxHealth: 700,
    attack: 80,
    trueDamage: 60,
    defence: 30,
    mods: [],
  },
  troll: {
    name: "Grump",
    icon: "👹",
    template: "troll",
    health: 350,
    maxHealth: 350,
    attack: 40,
    trueDamage: 20,
    defence: 15,
    mods: [],
  },
  manticore: {
    name: "Manny",
    icon: "🐯",
    template: "manticore",
    health: 400,
    maxHealth: 400,
    attack: 50,
    trueDamage: 30,
    defence: 20,
    mods: [],
  },
  ghoul: {
    name: "Spooky",
    icon: "👻",
    template: "ghoul",
    health: 250,
    maxHealth: 250,
    attack: 20,
    trueDamage: 10,
    defence: 10,
    mods: [],
  },
  faun: {
    name: "Pan",
    icon: "🐐",
    template: "faun",
    health: 180,
    maxHealth: 180,
    attack: 10,
    trueDamage: 5,
    defence: 15,
    mods: [],
  },
  satyr: {
    name: "Sylvan",
    icon: "🐐",
    template: "satyr",
    health: 200,
    maxHealth: 200,
    attack: 15,
    trueDamage: 10,
    defence: 20,
    mods: [],
  },
  wendigo: {
    name: "Frost",
    icon: "👹",
    template: "wendigo",
    health: 600,
    maxHealth: 600,
    attack: 70,
    trueDamage: 50,
    defence: 25,
    mods: [],
  },
  salamander: {
    name: "Lizard",
    icon: "🦎",
    template: "salamander",
    health: 150,
    maxHealth: 150,
    attack: 10,
    trueDamage: 5,
    defence: 5,
    mods: [],
  },
};

// Grouping of Creatures by Power Level
export const POWER_LEVELS = {
  weak: [
    CREATURES.fish,
    CREATURES.faun,
    CREATURES.salamander,
    CREATURES.harpy,
    CREATURES.unicorn,
  ],
  moderate: [
    CREATURES.alien,
    CREATURES.centaur,
    CREATURES.banshee,
    CREATURES.gryphon,
    CREATURES.vampire,
    CREATURES.troll,
    CREATURES.ghoul,
  ],
  strong: [
    CREATURES.dragon,
    CREATURES.pegasus,
    CREATURES.werewolf,
    CREATURES.basilisk,
    CREATURES.chimera,
    CREATURES.phoenix,
    CREATURES.manticore,
    CREATURES.sphinx,
  ],
  powerful: [
    CREATURES.minotaur,
    CREATURES.cyclops,
    CREATURES.hydra,
    CREATURES.cerberus,
    CREATURES.golem,
  ],
  legendary: [
    CREATURES.giant,
    CREATURES.kraken,
    CREATURES.wendigo,
    CREATURES.leviathan,
  ],
};

export const NEW_OBJ_FOR_CREATURES = {
  dragon: {
    id: 1,
    name: "Dragon",
    icon: "🐉",
    health: Math.round(BASE_HEALTH * 1.5),
    maxHealth: Math.round(BASE_HEALTH * 1.5),
    attack: Math.round(BASE_ATTACK * 1.2),
    defence: Math.round(BASE_DEFENCE * 1.0),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.3),
    mods: [],
  },
  unicorn: {
    id: 2,
    name: "Unicorn",
    icon: "🦄",
    health: Math.round(BASE_HEALTH * 1.1),
    maxHealth: Math.round(BASE_HEALTH * 1.1),
    attack: Math.round(BASE_ATTACK * 1.0),
    defence: Math.round(BASE_DEFENCE * 0.8),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.0),
    mods: [],
  },
  elephant: {
    id: 3,
    name: "Elephant",
    icon: "🐘",
    health: Math.round(BASE_HEALTH * 2.0),
    maxHealth: Math.round(BASE_HEALTH * 2.0),
    attack: Math.round(BASE_ATTACK * 0.8),
    defence: Math.round(BASE_DEFENCE * 1.8),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 0.7),
    mods: [],
  },
  alien: {
    id: 4,
    name: "Alien",
    icon: "👾",
    health: Math.round(BASE_HEALTH * 1.0),
    maxHealth: Math.round(BASE_HEALTH * 1.0),
    attack: Math.round(BASE_ATTACK * 1.4),
    defence: Math.round(BASE_DEFENCE * 0.6),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  phoenix: {
    id: 5,
    name: "Phoenix",
    icon: "🦅",
    health: Math.round(BASE_HEALTH * 1.3),
    maxHealth: Math.round(BASE_HEALTH * 1.3),
    attack: Math.round(BASE_ATTACK * 1.5),
    defence: Math.round(BASE_DEFENCE * 0.9),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.7),
    mods: [],
  },
  minotaur: {
    id: 6,
    name: "Minotaur",
    icon: "🐂",
    health: Math.round(BASE_HEALTH * 1.8),
    maxHealth: Math.round(BASE_HEALTH * 1.8),
    attack: Math.round(BASE_ATTACK * 1.6),
    defence: Math.round(BASE_DEFENCE * 1.5),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.2),
    mods: [],
  },
  werewolf: {
    id: 7,
    name: "Werewolf",
    icon: "🐺",
    health: Math.round(BASE_HEALTH * 1.2),
    maxHealth: Math.round(BASE_HEALTH * 1.2),
    attack: Math.round(BASE_ATTACK * 1.8),
    defence: Math.round(BASE_DEFENCE * 1.0),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.4),
    mods: [],
  },
  giant: {
    id: 8,
    name: "Giant",
    icon: "👹",
    health: Math.round(BASE_HEALTH * 2.5),
    maxHealth: Math.round(BASE_HEALTH * 2.5),
    attack: Math.round(BASE_ATTACK * 1.5),
    defence: Math.round(BASE_DEFENCE * 2.0),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  golem: {
    id: 9,
    name: "Golem",
    icon: "🗿",
    health: Math.round(BASE_HEALTH * 2.0),
    maxHealth: Math.round(BASE_HEALTH * 2.0),
    attack: Math.round(BASE_ATTACK * 1.0),
    defence: Math.round(BASE_DEFENCE * 2.5),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.0),
    mods: [],
  },
  vampire: {
    id: 10,
    name: "Vampire",
    icon: "🧛",
    health: Math.round(BASE_HEALTH * 1.1),
    maxHealth: Math.round(BASE_HEALTH * 1.1),
    attack: Math.round(BASE_ATTACK * 1.6),
    defence: Math.round(BASE_DEFENCE * 0.8),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  cyclops: {
    id: 11,
    name: "Cyclops",
    icon: "👁",
    health: Math.round(BASE_HEALTH * 1.8),
    maxHealth: Math.round(BASE_HEALTH * 1.8),
    attack: Math.round(BASE_ATTACK * 1.4),
    defence: Math.round(BASE_DEFENCE * 1.2),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.3),
    mods: [],
  },
  gryphon: {
    id: 12,
    name: "Gryphon",
    icon: "🦅",
    health: Math.round(BASE_HEALTH * 1.2),
    maxHealth: Math.round(BASE_HEALTH * 1.2),
    attack: Math.round(BASE_ATTACK * 1.4),
    defence: Math.round(BASE_DEFENCE * 1.1),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  kraken: {
    id: 13,
    name: "Kraken",
    icon: "🦑",
    health: Math.round(BASE_HEALTH * 2.2),
    maxHealth: Math.round(BASE_HEALTH * 2.2),
    attack: Math.round(BASE_ATTACK * 1.7),
    defence: Math.round(BASE_DEFENCE * 1.8),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  pegasus: {
    id: 14,
    name: "Pegasus",
    icon: "🦄",
    health: Math.round(BASE_HEALTH * 1.3),
    maxHealth: Math.round(BASE_HEALTH * 1.3),
    attack: Math.round(BASE_ATTACK * 1.1),
    defence: Math.round(BASE_DEFENCE * 1.0),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.1),
    mods: [],
  },
  banshee: {
    id: 15,
    name: "Banshee",
    icon: "👻",
    health: Math.round(BASE_HEALTH * 1.0),
    maxHealth: Math.round(BASE_HEALTH * 1.0),
    attack: Math.round(BASE_ATTACK * 1.5),
    defence: Math.round(BASE_DEFENCE * 0.7),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.4),
    mods: [],
  },
  chimera: {
    id: 16,
    name: "Chimera",
    icon: "🐉",
    health: Math.round(BASE_HEALTH * 1.8),
    maxHealth: Math.round(BASE_HEALTH * 1.8),
    attack: Math.round(BASE_ATTACK * 1.7),
    defence: Math.round(BASE_DEFENCE * 1.4),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.6),
    mods: [],
  },
  basilisk: {
    id: 17,
    name: "Basilisk",
    icon: "🐍",
    health: Math.round(BASE_HEALTH * 1.4),
    maxHealth: Math.round(BASE_HEALTH * 1.4),
    attack: Math.round(BASE_ATTACK * 1.3),
    defence: Math.round(BASE_DEFENCE * 1.1),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  centaur: {
    id: 18,
    name: "Centaur",
    icon: "🐎",
    health: Math.round(BASE_HEALTH * 1.3),
    maxHealth: Math.round(BASE_HEALTH * 1.3),
    attack: Math.round(BASE_ATTACK * 1.4),
    defence: Math.round(BASE_DEFENCE * 1.2),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.0),
    mods: [],
  },
  cerberus: {
    id: 19,
    name: "Cerberus",
    icon: "🐶",
    health: Math.round(BASE_HEALTH * 2.2),
    maxHealth: Math.round(BASE_HEALTH * 2.2),
    attack: Math.round(BASE_ATTACK * 1.8),
    defence: Math.round(BASE_DEFENCE * 1.7),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.6),
    mods: [],
  },
  hydra: {
    id: 20,
    name: "Hydra",
    icon: "🐍",
    health: Math.round(BASE_HEALTH * 2.0),
    maxHealth: Math.round(BASE_HEALTH * 2.0),
    attack: Math.round(BASE_ATTACK * 1.6),
    defence: Math.round(BASE_DEFENCE * 1.5),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.7),
    mods: [],
  },
  sphinx: {
    id: 21,
    name: "Sphinx",
    icon: "🦁",
    health: Math.round(BASE_HEALTH * 1.6),
    maxHealth: Math.round(BASE_HEALTH * 1.6),
    attack: Math.round(BASE_ATTACK * 1.4),
    defence: Math.round(BASE_DEFENCE * 1.2),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.1),
    mods: [],
  },
  harpy: {
    id: 22,
    name: "Harpy",
    icon: "🦅",
    health: Math.round(BASE_HEALTH * 1.2),
    maxHealth: Math.round(BASE_HEALTH * 1.2),
    attack: Math.round(BASE_ATTACK * 1.1),
    defence: Math.round(BASE_DEFENCE * 1.0),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.2),
    mods: [],
  },
  leviathan: {
    id: 23,
    name: "Leviathan",
    icon: "🐋",
    health: Math.round(BASE_HEALTH * 2.3),
    maxHealth: Math.round(BASE_HEALTH * 2.3),
    attack: Math.round(BASE_ATTACK * 1.8),
    defence: Math.round(BASE_DEFENCE * 1.9),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.8),
    mods: [],
  },
  yeti: {
    id: 24,
    name: "Yeti",
    icon: "🐾",
    health: Math.round(BASE_HEALTH * 1.7),
    maxHealth: Math.round(BASE_HEALTH * 1.7),
    attack: Math.round(BASE_ATTACK * 1.4),
    defence: Math.round(BASE_DEFENCE * 1.5),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.2),
    mods: [],
  },
  griffin: {
    id: 25,
    name: "Griffin",
    icon: "🦅",
    health: Math.round(BASE_HEALTH * 1.5),
    maxHealth: Math.round(BASE_HEALTH * 1.5),
    attack: Math.round(BASE_ATTACK * 1.3),
    defence: Math.round(BASE_DEFENCE * 1.2),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.3),
    mods: [],
  },
  naga: {
    id: 26,
    name: "Naga",
    icon: "🐍",
    health: Math.round(BASE_HEALTH * 1.4),
    maxHealth: Math.round(BASE_HEALTH * 1.4),
    attack: Math.round(BASE_ATTACK * 1.5),
    defence: Math.round(BASE_DEFENCE * 1.0),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  ogre: {
    id: 27,
    name: "Ogre",
    icon: "👹",
    health: Math.round(BASE_HEALTH * 2.0),
    maxHealth: Math.round(BASE_HEALTH * 2.0),
    attack: Math.round(BASE_ATTACK * 1.6),
    defence: Math.round(BASE_DEFENCE * 1.7),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.5),
    mods: [],
  },
  wendigo: {
    id: 28,
    name: "Wendigo",
    icon: "👹",
    health: Math.round(BASE_HEALTH * 2.0),
    maxHealth: Math.round(BASE_HEALTH * 2.0),
    attack: Math.round(BASE_ATTACK * 1.7),
    defence: Math.round(BASE_DEFENCE * 1.5),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.6),
    mods: [],
  },
  salamander: {
    id: 30,
    name: "Salamander",
    icon: "🦎",
    health: Math.round(BASE_HEALTH * 1.2),
    maxHealth: Math.round(BASE_HEALTH * 1.2),
    attack: Math.round(BASE_ATTACK * 1.0),
    defence: Math.round(BASE_DEFENCE * 1.0),
    trueDamage: Math.round(BASE_TRUE_DAMAGE * 1.2),
    mods: [],
  },
}
